<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 10pt; color: #1f2937; }
        h1 { font-size: 16pt; margin: 0 0 4pt; }
        h2 { font-size: 11pt; margin: 18pt 0 4pt; color: #374151; }
        .meta { color: #6b7280; margin-bottom: 12pt; font-size: 9pt; }
        .meta-row { margin: 2pt 0; }
        table { width: 100%; border-collapse: collapse; margin-top: 4pt; }
        th, td { padding: 5pt 6pt; border-bottom: 0.4pt solid #e5e7eb; text-align: left; font-size: 9pt; }
        th { background: #f3f4f6; font-weight: 700; }
        td.code { font-family: DejaVu Sans Mono, monospace; }
        .signature {
            margin-top: 30pt;
            display: table;
            width: 100%;
        }
        .signature .col { display: table-cell; width: 50%; padding-right: 12pt; }
        .signature .label { font-size: 8pt; color: #6b7280; }
        .signature .line { border-bottom: 0.4pt solid #6b7280; height: 30pt; margin: 4pt 0 2pt; }
        .footer { color: #9ca3af; font-size: 7pt; margin-top: 20pt; text-align: center; }
    </style>
</head>
<body>
    <h1>{{ config('app.name') }} — Employee Asset Summary</h1>
    <div class="meta">
        <div class="meta-row">Employee: <strong>{{ $employee->first_name }} {{ $employee->last_name }}</strong> ({{ $employee->code }})</div>
        @if($employee->position)
            <div class="meta-row">Position: {{ $employee->position }}</div>
        @endif
        @if($employee->department)
            <div class="meta-row">Department: {{ $employee->department->name }}</div>
        @endif
        @if($employee->branch)
            <div class="meta-row">Branch: {{ $employee->branch->name }}</div>
        @endif
        <div class="meta-row">Generated: {{ $generatedAt->format('Y-m-d H:i') }}</div>
    </div>

    <h2>Assigned assets ({{ $assets->count() }})</h2>
    @if($assets->isEmpty())
        <p style="color:#6b7280">No assets are currently assigned to this employee.</p>
    @else
        <table>
            <thead>
                <tr>
                    <th>Code</th>
                    <th>Category</th>
                    <th>Model</th>
                    <th>S/N</th>
                    <th>Branch</th>
                    <th>Supplier</th>
                </tr>
            </thead>
            <tbody>
                @foreach($assets as $asset)
                    <tr>
                        <td class="code">{{ $asset->code }}</td>
                        <td>{{ $asset->category?->name ?? '—' }}</td>
                        <td>{{ trim(($asset->assetModel?->manufacturer ?? '').' '.($asset->assetModel?->model_name ?? $asset->name ?? '')) ?: '—' }}</td>
                        <td class="code">{{ $asset->serial_number ?? '—' }}</td>
                        <td>{{ $asset->branch?->name ?? '—' }}</td>
                        <td>{{ $asset->supplier?->name ?? '—' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <div class="signature">
        <div class="col">
            <div class="label">Employee acknowledgement</div>
            <div class="line"></div>
            <div class="label">Signature &amp; date</div>
        </div>
        <div class="col">
            <div class="label">IT / HR signature</div>
            <div class="line"></div>
            <div class="label">Signature &amp; date</div>
        </div>
    </div>

    <div class="footer">Generated by {{ config('app.name') }} on {{ $generatedAt->toIso8601String() }}</div>
</body>
</html>
